trigger:
- master
- staging
- devops

pool:
  vmImage: 'ubuntu-18.04'

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.TargetBranch'], 'refs/heads/', '') ]
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    branchName: 'prod'

stages:
  - stage: Build
    displayName: 'Build and Publish WebApp'
    dependsOn: []
    jobs:
    - job: BuildPublish
      displayName: Build and Publish WebApp
      steps:
      - script: |
          echo $buildNumber
          echo $sourceVersion
          commitHash=${sourceVersion:0:7}
          version=${buildNumber}.${commitHash}
          echo $version
          echo $commitHash
          echo "##vso[task.setvariable variable=version]$version"
          echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
        env: { sourceVersion: $(Build.SourceVersion), buildNumber: $(Build.BuildNumber) }
        displayName: Generate Variables
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'
      - script: |
          yarn global add @angular/cli@11
          yarn install
          yarn generate
        displayName: 'yarn install'
      - script: yarn build:$(branchName)
        displayName: 'Build app $(branchName)'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        displayName: 'Copy files to artifact folder'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: boardroom-portal
        displayName: 'Publish artifact'
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Azure MPN'
          appName: '-boardroom-portal'
          package: $(Build.ArtifactStagingDirectory)/**/*.zip
        displayName: 'publish to webapp'
