trigger:
- master
- staging
- devops

pool:
  vmImage: 'ubuntu-18.04'

variables:
  DOCKER_BUILDKIT: 1

stages:
  - stage: Build
    displayName: 'Build and Publish Docker'
    dependsOn: []
    jobs:
    - job: Docker
      displayName: Build and Publish docker image
      steps:
      - script: |
          echo $buildNumber
          echo $sourceVersion
          commitHash=${sourceVersion:0:7}
          version=${buildNumber}.${commitHash}
          echo $version
          echo $commitHash
          echo "##vso[task.setvariable variable=version]$version"
          echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
        env: { sourceVersion: $(Build.SourceVersion), buildNumber: $(Build.BuildNumber) }
        displayName: Generate Variables
      - template: pipeline/template/docker.yml
        parameters:
          version: $(version)
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
            profile: dev
            tags: |
              latest
              dev
              dev-latest
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
            profile: staging
            tags: |
              staging
              staging-latest
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
            profile: prod
            tags: |
              stable
              stable-latest
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/devops') }}:
            profile: dev
            tags: |
              devops
